# -*- mode: python ; coding: utf-8 -*-

import os

target_arch = os.environ.get("TARGET_ARCH") or None
localizations = [
    "en",
    "vi",
    "ko",
    "ja",
    "zh-Hans",
    "zh-Hant",
    "es",
    "pt-BR",
    "pt-PT",
    "fr",
    "de",
    "it",
    "ru",
    "uk",
    "pl",
    "nl",
    "tr",
    "ar",
    "fa",
    "he",
    "hi",
    "bn",
    "ur",
    "id",
    "ms",
    "th",
    "fil",
    "ro",
    "cs",
    "el",
]

datas = [
    ("assets/app-icon-source.png", "assets"),
    ("LICENSE", "licenses"),
    ("THIRD_PARTY_NOTICES.md", "licenses"),
    (".build-licenses", "licenses"),
    ("translations/*.qm", "translations"),
]
binaries = []
hiddenimports = [
    "keyring.backends.macOS",
    "send2trash.mac",
    "app_paths",
    "audio_activity",
    "chunker",
    "dependencies",
    "extractor",
    "i18n",
    "languages",
    "media_launcher",
    "muxer",
    "network_tls",
    "open_subtitles",
    "pipeline",
    "settings",
    "subtitle_sync",
    "translator",
    "ui",
]

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "PySide6.Qt3DAnimation",
        "PySide6.Qt3DCore",
        "PySide6.Qt3DExtras",
        "PySide6.Qt3DInput",
        "PySide6.Qt3DLogic",
        "PySide6.Qt3DRender",
        "PySide6.QtBluetooth",
        "PySide6.QtCharts",
        "PySide6.QtDataVisualization",
        "PySide6.QtLocation",
        "PySide6.QtMultimedia",
        "PySide6.QtNetworkAuth",
        "PySide6.QtNfc",
        "PySide6.QtPdf",
        "PySide6.QtPositioning",
        "PySide6.QtQuick",
        "PySide6.QtQuick3D",
        "PySide6.QtRemoteObjects",
        "PySide6.QtScxml",
        "PySide6.QtSensors",
        "PySide6.QtSerialBus",
        "PySide6.QtSerialPort",
        "PySide6.QtSql",
        "PySide6.QtStateMachine",
        "PySide6.QtTest",
        "PySide6.QtWebChannel",
        "PySide6.QtWebEngineCore",
        "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebSockets",
    ],
    noarchive=False,
    optimize=1,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="SubtitleTranslator",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=target_arch,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="SubtitleTranslator",
)
app = BUNDLE(
    coll,
    name="SubtitleTranslator.app",
    icon="assets/SubtitleTranslator.icns",
    bundle_identifier="com.danielpberg.subtitletranslator",
    info_plist={
        "CFBundleDisplayName": "SubtitleTranslator",
        "CFBundleDevelopmentRegion": "en",
        "CFBundleLocalizations": localizations,
        "CFBundleShortVersionString": "0.9.0",
        "CFBundleVersion": "0.9.0.11",
        "LSMinimumSystemVersion": "13.0",
        "NSHighResolutionCapable": True,
        "NSAppleEventsUsageDescription": (
            "SubtitleTranslator opens Terminal only when you approve a "
            "Homebrew media-tool installation."
        ),
        "NSHumanReadableCopyright": "Copyright 2026 Daniel Berg",
    },
)
